_extends: .github
tag-template: secone-security-$NEXT_MINOR_VERSION

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What’s Changed

  $CHANGES
